### ISSUE TITLE
Upgrade azurerm dependency to at least 2.28 to support role_definition_resource_id

### ISSUE THREAD

**Issue by marcosgm** [lacework/terraform-azure-activity-log#21]
We have a version mismatch in the latest Azure module:
terraform apply
╷
│ Error: Unsupported attribute
│
│   on .terraform/modules/az_activity_log/main.tf line 128, in resource “azurerm_role_assignment” “lacework”:
│  128:   role_definition_id = azurerm_role_definition.lacework.role_definition_resource_id
│
│ This object has no argument, nested block, or exported attribute named “role_definition_resource_id”.
That “role_definition_resource_id” doesn’t exist in 2.26 (nor in 2.27, it appeared in 2.28) https://registry.terraform.io/providers/hashicorp/azurerm/2.26.0/docs/resources/role_assignment , which is the version we require in https://support.lacework.com/hc/en-us/articles/360057092134-Azure-Compliance-Activity-Log-Integrations-Terraform-using-Azure-Cloud-Shell. 

I'd suggest bumping the dependencies to latest, which works fine (2.67). 2.28 also works fine

**Comment by marcosgm** [comment]
related https://github.com/lacework/terraform-azure-activity-log/pull/18/commits/258f8d6753f8b795c2b81f8a356cee86144240d6

**Comment by afiune** [comment]
https://lacework.atlassian.net/browse/ALLY-588

**Comment by marcosgm** [comment]
https://github.com/lacework/terraform-azure-config/pull/18
