### ISSUE TITLE
Warning that AzureRM Provider changes syntax in 4.0

### ISSUE THREAD

**Issue by johgoe** [lacework/terraform-azure-activity-log#84]
**Describe the bug**
Warning that azurerm_monitor_diagnostic_setting log should be replayed by enabled_log

The warning in shell is
```
  with module.az_activity_log.azurerm_monitor_diagnostic_setting.lacework,
│   on .terraform/modules/az_activity_log/main.tf line 105, in resource "azurerm_monitor_diagnostic_setting" "lacework":
│  105: resource "azurerm_monitor_diagnostic_setting" "lacework" {
│ 
│ `log` has been superseded by `enabled_log` and will be removed in version 4.0
│ of the AzureRM Provider.
```

**Steps to reproduce**
terraform init
terraform apply

**Expected behavior**
Ready for AzureRM Provider 4.0.0

**Please complete the following information):**
Terraform v1.5.2
on linux_amd64
+ provider registry.terraform.io/hashicorp/azuread v2.39.0
+ provider registry.terraform.io/hashicorp/azurerm v3.64.0
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/time v0.9.1
+ provider registry.terraform.io/lacework/lacework v1.9.0

**Additional info**

According to https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting.html
the new syntax of 

https://github.com/lacework/terraform-azure-activity-log/blob/9be1685cbdeb4a4c28d722bd184f400cf185ef62/main.tf#L112-L143

should look like this

```
  enabled_log {
    category = "Administrative"
  }
  enabled_log {
    category = "Security"
  }
  enabled_log {
    category = "Alert"
  }
  enabled_log {
    category = "Policy"
  }
  enabled_log {
    category = "ResourceHealth"
  }
  enabled_log {
    category = "Autoscale"
  }
  enabled_log {
    category = "Recommendation"
  }
  enabled_log {
    category = "ServiceHealth"
  }

```

**Comment by afiune** [comment]
@johgoe Thank you for your feedback! We will prioritize this work and keep you posted of any progress.

Internal Ticket: https://lacework.atlassian.net/browse/GROW-2311

**Comment by dmurray-lacework** [comment]
Hi @johgoe, thanks for raising this issue. We have raised a PR and will be keeping track of the [AzureRM](https://github.com/hashicorp/terraform-provider-azurerm) releases. We will await the release of the provider version before updating the terraform-azure-activity-log module

Draft PR for the changes -> https://github.com/lacework/terraform-azure-activity-log/pull/85/files
I will close out this task and any discussion can take place on the PR.

Thanks again for raising the issue!
